name: aninet
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  tflite: any
  image_picker: any
  cupertino_icons: ^0.1.3
  flutter_launcher_icons: ^0.8.0
  firebase_core: ^0.5.3
  firebase_storage: ^5.0.0
  dropdown_formfield: ^0.1.3
  camera: 0.5.7
  http:
  shared_preferences: ^0.5.12
  animations:
  awesome_dialog:
  dynamic_theme: ^1.0.0
  rich_text_controller: ^1.1.0
  introduction_screen: ^1.0.9
  permission_handler: ^5.0.0
  flutter_gradient_colors: ^1.0.0
  flutter_color: any
  shape_of_view: ^1.0.2
  audioplayers: ^0.16.1
  video_player: 0.10.11
  flutter_video_info: ^1.0.1
  path_provider: ^1.6.14
  file_picker: ^1.13.0+1
  folder_file_saver: 1.0.0+2
  flutter_downloader: ^1.5.2
  font_awesome_flutter: any
  location: ^3.0.0
  url_launcher: ^5.7.6
  flutter_open_whatsapp: ^0.1.2
  google_sign_in: ^4.5.6
  country_picker: ^1.1.3
  avatar_glow: any
  dio: ^3.0.10
  firebase_auth: ^0.18.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_native_splash: ^0.1.9



# The following section is specific to Flutter.
flutter:


  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/audio/
    - assets/model/
    - assets/videos/
    - server/node_modules/saslprep/lib/
    - server/node_modules/saslprep/test/
    - server/node_modules/mongoose/lib/
    - server/node_modules/mongoose/tools/
    - server/node_modules/mongoose/dist/
    - server/node_modules/mongoose/node_modules/
    - server/node_modules/bluebird/js/
    - server/node_modules/mongodb/lib/
    - server/node_modules/core-util-is/lib/
    - server/node_modules/express/lib/
    - server/node_modules/regexp-clone/test/
    - server/node_modules/semver/bin/
    - server/node_modules/mquery/node_modules/
    - server/node_modules/mquery/lib/
    - server/node_modules/string_decoder/lib/
    - server/node_modules/mquery/test/
    - server/node_modules/kareem/test/
    - server/node_modules/setprototypeof/test/
    - server/node_modules/@types/mongodb/
    - server/node_modules/@types/node/
    - server/node_modules/mpath/lib/
    - server/node_modules/sift/coverage/
    - server/node_modules/sift/src/
    - server/node_modules/@types/bson/
    - server/node_modules/mpath/test/
    - server/node_modules/sift/lib/
    - server/node_modules/readable-stream/lib/
    - server/node_modules/send/node_modules/
    - server/node_modules/readable-stream/doc/
    - server/node_modules/debug/src/
    - server/node_modules/sift/test/
    - server/node_modules/require_optional/test/
    - server/node_modules/bson/lib/bson/
    - server/node_modules/depd/lib/compat/
    - server/node_modules/depd/lib/browser/
    - server/node_modules/send/node_modules/ms/
    - server/node_modules/safe-buffer/
    - server/node_modules/ee-first/
    - server/node_modules/range-parser/
    - server/node_modules/bytes/
    - server/node_modules/mquery/
    - server/node_modules/express/
    - server/node_modules/encodeurl/
    - server/node_modules/string_decoder/
    - server/node_modules/merge-descriptors/
    - server/node_modules/array-flatten/
    - server/node_modules/methods/
    - server/node_modules/bl/
    - server/node_modules/proxy-addr/
    - server/node_modules/mpath/
    - server/node_modules/depd/
    - server/node_modules/core-util-is/
    - server/node_modules/require_optional/
    - server/node_modules/memory-pager/
    - server/node_modules/@types/
    - server/node_modules/process-nextick-args/
    - server/node_modules/.bin/
    - server/node_modules/toidentifier/
    - server/node_modules/content-type/
    - server/node_modules/kareem/
    - server/node_modules/ms/
    - server/node_modules/content-disposition/
    - server/
    - server/node_modules/
    - server/node_modules/bson/
    - server/node_modules/destroy/
    - server/node_modules/sift/
    - server/node_modules/@types/node/ts3.6/
    - server/node_modules/@types/node/ts3.4/
    - server/node_modules/@types/node/fs/
    - server/node_modules/mquery/node_modules/debug/
    - server/node_modules/express/lib/middleware/
    - server/node_modules/mquery/lib/collection/
    - server/node_modules/mquery/test/collection/
    - server/node_modules/mongodb/lib/async/
    - server/node_modules/mongodb/lib/cmap/
    - server/node_modules/mongodb/lib/operations/
    - server/node_modules/mongodb/lib/topologies/
    - server/node_modules/mongodb/lib/gridfs/
    - server/node_modules/express/lib/router/
    - server/node_modules/mongodb/lib/bulk/
    - server/node_modules/mongodb/lib/core/
    - server/node_modules/bluebird/js/release/
    - server/node_modules/bluebird/js/browser/
    - server/node_modules/mongoose/lib/options/
    - server/node_modules/mongodb/lib/gridfs-stream/
    - server/node_modules/mongoose/lib/schema/
    - server/node_modules/mongoose/lib/types/
    - server/node_modules/mongoose/lib/drivers/
    - server/node_modules/mongoose/lib/cursor/
    - server/node_modules/mongoose/lib/plugins/
    - server/node_modules/mongoose/lib/cast/
    - server/node_modules/mongoose/lib/error/
    - server/node_modules/mongoose/lib/helpers/
    - server/node_modules/mongoose/node_modules/ms/
    - server/node_modules/mongoose/node_modules/safe-buffer/
    - server/.git/objects/47/
    - server/.git/objects/fa/
    - server/.git/objects/af/
    - server/.git/objects/1e/
    - server/.git/objects/1b/
    - server/.git/objects/3a/
    - server/node_modules/body-parser/lib/types/
    - server/.git/objects/3b/
    - server/.git/objects/3c/
    - server/.git/objects/7a/
    - server/node_modules/iconv-lite/encodings/tables/
    - server/.git/objects/40/
    - server/.git/objects/41/
    - server/.git/objects/42/
    - server/.git/objects/43/
    - server/.git/objects/44/
    - server/.git/objects/45/
    - server/.git/objects/46/
    - server/.git/objects/52/
    - server/.git/objects/53/
    - server/.git/objects/54/
    - server/node_modules/require_optional/test/nestedTest/
    - server/.git/objects/55/
    - server/.git/objects/56/
    - server/.git/objects/57/
    - server/.git/objects/58/
    - server/.git/objects/59/
    - server/.git/objects/3d/
    - server/.git/objects/3e/
    - server/.git/objects/3f/
    - server/.git/objects/29/
    - server/node_modules/readable-stream/doc/wg-meetings/
    - server/.git/objects/28/
    - server/node_modules/readable-stream/lib/internal/
    - server/.git/objects/27/
    - server/.git/objects/83/
    - server/.git/objects/50/
    - server/.git/objects/17/
    - server/.git/objects/23/
    - server/.git/objects/60/
    - server/.git/objects/61/
    - server/.git/objects/62/
    - server/.git/objects/63/
    - server/.git/objects/64/
    - server/.git/objects/65/
    - server/.git/objects/4a/
    - server/.git/objects/4b/
    - server/.git/objects/4c/
    - server/.git/objects/4d/
    - server/.git/objects/4e/
    - server/node_modules/bson/lib/bson/parser/
    - server/.git/objects/4f/
    - server/.git/objects/19/
    - server/.git/objects/76/
    - server/.git/objects/a5/
    - server/.git/objects/a6/
    - server/.git/objects/a7/
    - server/.git/objects/a8/
    - server/.git/objects/5a/
    - server/.git/objects/5b/
    - server/.git/objects/5d/
    - server/.git/objects/5e/
    - server/.git/objects/66/
    - server/.git/objects/67/
    - server/.git/objects/68/
    - server/node_modules/bson/lib/
    - server/.git/objects/69/
    - server/.git/objects/a1/
    - server/.git/objects/a2/
    - server/.git/objects/a3/
    - server/.git/objects/a4/
    - server/.git/objects/75/
    - server/.git/objects/cc/
    - server/.git/objects/77/
    - server/.git/objects/78/
    - server/.git/objects/b0/
    - server/.git/objects/b1/
    - server/node_modules/mquery/node_modules/debug/src/
    - server/.git/objects/b2/
    - server/.git/objects/b3/
    - server/.git/objects/5f/
    - server/.git/objects/9f/
    - server/.git/objects/ef/
    - server/.git/objects/70/
    - server/.git/objects/71/
    - server/.git/objects/72/
    - server/.git/objects/73/
    - server/.git/objects/74/
    - server/.git/objects/6d/
    - server/.git/objects/6e/
    - server/.git/objects/6f/
    - server/.git/objects/a0/
    - server/.git/objects/aa/
    - server/.git/objects/ab/
    - server/node_modules/mongodb/lib/core/tools/
    - server/.git/objects/ac/
    - server/node_modules/mongodb/lib/core/connection/
    - server/.git/objects/ad/
    - server/node_modules/mongodb/lib/core/auth/
    - server/.git/objects/b4/
    - server/.git/objects/b5/
    - server/.git/objects/b6/
    - server/.git/objects/b7/
    - server/.git/objects/b8/
    - server/.git/objects/6a/
    - server/.git/objects/6b/
    - server/.git/objects/6c/
    - server/.git/objects/88/
    - server/node_modules/mongodb/lib/core/wireprotocol/
    - server/.git/objects/c0/
    - server/.git/objects/c1/
    - server/.git/objects/99/
    - server/.git/objects/c3/
    - server/.git/objects/c4/
    - server/.git/objects/c5/
    - server/.git/objects/c6/
    - server/.git/objects/ae/
    - server/.git/objects/81/
    - server/.git/objects/8a/
    - server/.git/objects/bf/
    - server/node_modules/mongodb/lib/core/topologies/
    - server/.git/objects/84/
    - server/node_modules/mongodb/lib/core/sdam/
    - server/.git/objects/85/
    - server/.git/objects/86/
    - server/.git/objects/87/
    - server/.git/objects/c2/
    - server/.git/objects/ba/
    - server/.git/objects/bb/
    - server/.git/objects/bc/
    - server/.git/objects/bd/
    - server/.git/objects/be/
    - server/.git/objects/91/
    - server/.git/objects/92/
    - server/.git/objects/c7/
    - server/.git/objects/c8/
    - server/.git/objects/c9/
    - server/.git/objects/7b/
    - server/.git/objects/7c/
    - server/.git/objects/7d/
    - server/.git/objects/7e/
    - server/.git/objects/7f/
    - server/.git/refs/
    - server/.git/objects/d2/
    - server/.git/objects/d3/
    - server/.git/objects/d4/
    - server/.git/objects/
    - server/.git/objects/d5/
    - server/.git/info/
    - server/.git/objects/d6/
    - server/.git/objects/d7/
    - server/.git/branches/
    - server/.git/refs/heads/
    - server/.git/objects/d8/
    - server/.git/refs/tags/
    - server/.git/objects/d9/
    - server/.git/objects/93/
    - server/.git/objects/94/
    - server/.git/objects/95/
    - server/.git/objects/96/
    - server/.git/objects/97/
    - server/.git/
    - server/.git/objects/98/
    - server/.git/objects/d0/
    - server/.git/hooks/
    - server/.git/objects/d1/
    - server/.git/objects/info/
    - server/.git/objects/cd/
    - server/.git/objects/ce/
    - server/.git/objects/cf/
    - server/.git/objects/06/
    - server/.git/objects/e0/
    - server/node_modules/ecdsa-sig-formatter/src/
    - server/.git/objects/e1/
    - server/.git/logs/
    - server/.git/objects/e2/
    - server/.git/objects/79/
    - server/.git/objects/80/
    - server/.git/objects/8d/
    - server/.git/objects/8e/
    - server/.git/objects/8f/
    - server/.git/objects/pack/
    - server/.git/objects/ca/
    - server/.git/objects/cb/
    - server/.git/objects/2a/
    - server/.git/objects/9c/
    - server/.git/objects/2b/
    - server/.git/objects/9d/
    - server/.git/objects/2c/
    - server/.git/objects/9e/
    - server/node_modules/jsonwebtoken/node_modules/ms/
    - server/.git/objects/02/
    - server/.git/objects/2e/
    - server/.git/objects/03/
    - server/.git/objects/2f/
    - server/.git/objects/04/
    - server/.git/objects/05/
    - server/.git/logs/refs/remotes/origin/
    - server/.git/objects/da/
    - server/.git/refs/remotes/
    - server/.git/objects/e3/
    - server/.git/objects/37/
    - server/.git/objects/e4/
    - server/.git/objects/38/
    - server/.git/objects/e5/
    - server/.git/objects/39/
    - server/.git/objects/e6/
    - server/.git/objects/01/
    - server/.git/objects/e7/
    - server/.git/objects/89/
    - server/.git/objects/a9/
    - server/.git/objects/00/
    - server/.git/objects/9a/
    - server/.git/objects/18/
    - server/.git/objects/9b/
    - server/.git/objects/f2/
    - server/.git/objects/f3/
    - server/.git/objects/f4/
    - server/.git/objects/f5/
    - server/.git/objects/f6/
    - server/.git/objects/b9/
    - server/.git/objects/f8/
    - server/.git/objects/f9/
    - server/.git/logs/refs/remotes/heroku/
    - server/.git/objects/07/
    - server/node_modules/jsonwebtoken/lib/
    - server/.git/objects/08/
    - server/.git/logs/refs/heads/
    - server/.git/objects/09/
    - server/.git/logs/refs/remotes/
    - server/.git/objects/de/
    - server/.git/objects/df/
    - server/.git/logs/refs/
    - server/.git/objects/82/
    - server/.git/objects/f0/
    - server/.git/objects/f1/
    - server/node_modules/jsonwebtoken/node_modules/
    - server/.git/objects/ec/
    - server/.git/objects/ed/
    - server/.git/objects/ee/
    - server/.git/objects/dd/
    - server/.git/objects/dc/
    - server/.git/objects/db/
    - server/.git/objects/0a/
    - server/.git/objects/0b/
    - server/.git/objects/10/
    - server/.git/objects/11/
    - server/.git/objects/12/
    - server/.git/objects/13/
    - server/routes/
    - server/.git/objects/14/
    - server/middleware/
    - server/.git/objects/15/
    - server/controllers/
    - server/.git/objects/16/
    - server/models/
    - server/node_modules/jws/lib/
    - server/.git/objects/eb/
    - server/.git/objects/20/
    - server/.git/objects/21/
    - server/.git/objects/22/
    - server/.git/objects/f7/
    - server/.git/refs/remotes/heroku/
    - server/.git/objects/24/
    - server/.git/objects/25/
    - server/.git/objects/26/
    - server/.git/objects/fb/
    - server/.git/objects/0c/
    - server/.git/objects/0d/
    - server/.git/objects/0e/
    - server/.git/objects/0f/
    - server/.git/objects/8c/
    - server/node_modules/mime/src/
    - server/.git/objects/49/
    - server/.git/objects/8b/
    - server/.git/objects/48/
    - server/.git/objects/1d/
    - server/node_modules/jwa/
    - server/.git/objects/ea/
    - server/node_modules/jsonwebtoken/
    - server/.git/objects/1f/
    - server/node_modules/lodash.once/
    - server/.git/objects/90/
    - server/node_modules/lodash.isstring/
    - server/.git/objects/30/
    - server/node_modules/jws/
    - server/node_modules/buffer-equal-constant-time/
    - server/node_modules/lodash.isinteger/
    - server/node_modules/lodash.isboolean/
    - server/.git/objects/fc/
    - server/node_modules/depd/lib/
    - server/.git/objects/fd/
    - server/.git/objects/fe/
    - server/.git/objects/ff/
    - server/.git/objects/e9/
    - server/.git/objects/1a/
    - server/.git/objects/e8/
    - server/.git/objects/1c/
    - server/node_modules/ecdsa-sig-formatter/
    - server/.git/objects/33/
    - server/node_modules/mongoose/lib/schema/operators/
    - server/node_modules/lodash.isnumber/
    - server/node_modules/lodash.isplainobject/
    - server/node_modules/lodash.includes/
    - server/.git/objects/31/
    - server/.git/objects/32/
    - server/node_modules/mongoose/lib/drivers/node-mongodb-native/
    - server/node_modules/mongoose/lib/drivers/browser/
    - server/node_modules/mongoose/lib/helpers/schematype/
    - server/node_modules/mongoose/lib/helpers/topology/
    - server/node_modules/mongoose/lib/helpers/schema/
    - server/node_modules/mongoose/lib/helpers/discriminator/
    - server/node_modules/mongoose/lib/helpers/timestamps/
    - server/node_modules/mongoose/lib/helpers/update/
    - server/node_modules/mongoose/lib/helpers/cursor/
    - server/node_modules/mongoose/lib/helpers/aggregate/
    - server/node_modules/mongoose/lib/helpers/populate/
    - server/node_modules/mongoose/lib/helpers/document/
    - server/node_modules/mongoose/lib/helpers/query/
    - server/node_modules/mongoose/lib/helpers/projection/
    - server/node_modules/mongoose/lib/helpers/indexes/
    - server/node_modules/mongoose/lib/helpers/model/
    - server/node_modules/body-parser/lib/
    - server/node_modules/readable-stream/lib/internal/streams/
    - server/node_modules/bson/browser_build/
    - server/node_modules/qs/lib/
    - server/node_modules/qs/test/
    - server/node_modules/qs/dist/
    - server/node_modules/readable-stream/
    - server/node_modules/on-finished/
    - server/node_modules/debug/
    - server/node_modules/media-typer/
    - server/node_modules/mime-db/
    - server/node_modules/setprototypeof/
    - server/node_modules/bl/test/
    - server/node_modules/statuses/
    - server/node_modules/parseurl/
    - server/node_modules/etag/
    - server/node_modules/isarray/
    - server/node_modules/saslprep/
    - server/node_modules/resolve-from/
    - server/node_modules/send/
    - server/node_modules/finalhandler/
    - server/node_modules/utils-merge/
    - server/node_modules/denque/
    - server/node_modules/serve-static/
    - server/node_modules/sliced/
    - server/node_modules/mime/
    - server/node_modules/ipaddr.js/
    - server/node_modules/cookie/
    - server/node_modules/escape-html/
    - server/.git/objects/35/
    - server/node_modules/bluebird/
    - server/node_modules/negotiator/lib/
    - server/.git/objects/36/
    - server/node_modules/semver/
    - server/node_modules/http-errors/
    - server/node_modules/accepts/
    - server/node_modules/cookie-signature/
    - server/node_modules/forwarded/
    - server/node_modules/negotiator/
    - server/node_modules/body-parser/
    - server/node_modules/mongoose-legacy-pluralize/
    - server/node_modules/mongodb/
    - server/node_modules/mongoose/
    - server/node_modules/sparse-bitfield/
    - server/node_modules/vary/
    - server/node_modules/unpipe/
    - server/node_modules/util-deprecate/
    - server/.git/objects/34/
    - server/node_modules/raw-body/
    - server/node_modules/iconv-lite/
    - server/node_modules/fresh/
    - server/node_modules/qs/
    - server/node_modules/path-to-regexp/
    - server/node_modules/safer-buffer/
    - server/.git/refs/remotes/origin/
    - server/node_modules/mime-types/
    - server/node_modules/regexp-clone/
    - server/node_modules/type-is/
    - server/node_modules/iconv-lite/lib/
    - server/node_modules/inherits/
    - server/node_modules/ipaddr.js/lib/
    - server/node_modules/iconv-lite/encodings/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
